const { SITE, PROJECTS, EXPERIMENTS, KNOWLEDGE, CONNECTIONS, SYSTEMS_TOPICS, MEM, ACTIVITY, MEMBERS, NEWS } = window;
const h = value => String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const rows = data => `<dl class="spec">${data.map(([k,v])=>`<div class="spec-row"><dt>${h(k)}</dt><dd>${h(v)}</dd></div>`).join("")}</dl>`;
const tags = list => `<div class="entry-tags">${list.map(x=>`<span class="tag">${h(x)}</span>`).join("")}</div>`;
function sectionHead(title,note){return `<div class="sec-h"><h2>${h(title)}</h2><span class="line"></span><span class="n">${h(note)}</span></div>`}
function projectEntry(p){return `<article class="entry"><div class="entry-id">[${p.id}]</div><div><h3 class="entry-title"><a href="#/projects/${p.slug}">${h(p.title)}</a></h3><p class="entry-desc">${h(p.blurb)}</p>${tags(p.tags)}</div><div class="entry-side"><span class="tag ${p.status==='active'?'a':''}">${h(p.status)}</span></div></article>`}
function stats(){return `<div class="statbar"><div><b>${NEWS.length}</b><span>dispatches</span></div><div><b>${EXPERIMENTS.length}</b><span>experiments</span></div><div><b>${KNOWLEDGE.reduce((n,x)=>n+x.leaves.length,0)}</b><span>reference notes</span></div><div><b>${PROJECTS.length}</b><span>builds</span></div></div>`}
function activityFeed(){return `<div class="panel"><div class="panel-b" style="padding:0">${ACTIVITY.map(a=>`<div style="display:grid;grid-template-columns:80px 1fr;gap:13px;padding:12px 15px;border-bottom:1px solid var(--line);font-size:11.5px"><span class="exp-id">@${h(a.who)}</span><span style="color:var(--fg2)">${h(a.verb)} <a href="${a.ref}" style="border:0;color:var(--fg)">${h(a.target)}</a></span></div>`).join("")}</div></div>`}
function memberCard(m){return `<a href="${m.link}" style="border:0;display:block"><div class="panel"><div class="panel-h">dossier <span class="r">clearance: ${h(m.clearance)}</span></div><div class="panel-b"><div style="display:flex;justify-content:space-between;align-items:baseline"><b style="font-size:14px;color:var(--fg)">${h(m.name)}</b><span class="tag ok">${h(m.status)}</span></div><div style="margin-top:2px;color:var(--fg4);font-size:10px;letter-spacing:.08em;text-transform:uppercase">${h(m.role)} / @${h(m.handle)}</div><div style="margin-top:9px;color:var(--fg3);font-size:11.5px">${h(m.identity)}</div><div class="entry-tags" style="margin-top:11px">${m.focus.map(x=>`<span class="tag">${h(x)}</span>`).join("")}</div></div></div></a>`}
function newsItem(n){return `<article class="entry"><div class="entry-id">[${n.id}]</div><div><h3 class="entry-title"><span class="tag a" style="margin-right:9px">${h(n.tag)}</span>${h(n.title)}</h3><p class="entry-desc">${h(n.body)}</p><div style="margin-top:9px;color:var(--fg4);font-size:10px;letter-spacing:.08em;text-transform:uppercase">${h(n.date)}${n.ref?` · <a href="${n.ref}" style="border:0;color:var(--fg4)">related \u2192</a>`:''}</div></div></article>`}
function newsPreview(n){return `<div style="display:grid;grid-template-columns:52px 1fr auto;gap:20px;padding:15px 0;border-top:1px solid var(--line)"><span class="exp-id">[${n.id}]</span><span><span class="tag a" style="margin-right:9px">${h(n.tag)}</span>${h(n.title)}</span><span class="exp-id">${h(n.date)}</span></div>`}
function Home(){return `<div class="view"><section class="hero"><div class="container"><div class="kicker">// larpsociety / dispatches on AI, systems, and OSINT</div><h1 style="max-width:26ch">Field notes from the edges of AI, systems, and OSINT<span class="cur"></span></h1><p class="lede" style="margin-top:18px;max-width:70ch">Short dispatches, logged experiments, and reference notes on machine learning, low-level systems, and OSINT methodology. Written and run by one operator — public because the work is public.</p><div class="linkrow"><a class="btn solid" href="#/news">read dispatches &rarr;</a><a class="btn" href="#/resources">resources &rarr;</a><a class="btn" href="#/lab">lab &rarr;</a></div></div></section><section class="sec"><div class="container">${stats()}</div></section><section class="sec"><div class="container">${sectionHead('dispatches','latest')}${NEWS.slice(0,4).map(newsItem).join('')}<div class="linkrow"><a class="btn" href="#/news">all dispatches &rarr;</a></div></div></section><section class="sec"><div class="container">${sectionHead('lab','recent experiments')}${EXPERIMENTS.slice(0,3).map(e=>`<div class="exp"><div style="display:grid;grid-template-columns:52px 1fr auto;gap:20px;padding:15px 0;align-items:baseline"><span class="exp-id">[${e.id}]</span><span class="exp-title">${h(e.title)}</span><span class="tag ${e.tag}">${h(e.status)}</span></div></div>`).join('')}<div class="linkrow"><a class="btn" href="#/lab">full lab log &rarr;</a></div></div></section><section class="sec"><div class="container">${sectionHead('resources','reference library')}<p class="lede dim mb">AI, mathematics, C, systems, OSINT — concepts kept connected to the work instead of floating as disconnected definitions.</p><div class="linkrow"><a class="btn" href="#/resources">browse resources &rarr;</a><a class="btn" href="#/projects">see the builds &rarr;</a></div></div></section><section class="sec"><div class="container">${sectionHead('operator','who runs this')}${memberCard(MEMBERS[0])}<div class="linkrow" style="margin-top:16px"><a class="btn" href="#/operator">full profile &rarr;</a></div></div></section></div>`}
function Projects(){return `<div class="view"><section class="sec container">${sectionHead('projects','built things')}<p class="lede dim mb">Projects are presented as technical systems: what goes in, what happens, what comes out, and which abstractions were removed.</p>${PROJECTS.map(projectEntry).join('')}</section></div>`}
function ProjectDetail(){const slug=currentPath().split('/')[2],p=PROJECTS.find(x=>x.slug===slug);if(!p)return NotFound();const ex=EXPERIMENTS.filter(e=>p.related.includes(e.id));const source=p.spec.find(x=>x[0]==='source')?.[1];return `<div class="view"><section class="sec container"><div class="kicker"><a href="#/projects" style="border:0">projects</a> / ${h(p.slug)}</div><h1 style="font-size:clamp(22px,4vw,34px);margin-top:16px">${h(p.title)}</h1><p class="lede" style="margin-top:14px">${h(p.blurb)}</p>${tags(p.tags)}</section><section class="sec"><div class="container">${sectionHead('specification','['+p.id+']')}<div class="panel"><div class="panel-h">system profile <span class="r">LARPSOCIETY</span></div><div class="panel-b">${rows(p.spec)}</div></div></div></section><section class="sec"><div class="container">${sectionHead('pipeline','flow')}<ol class="chain">${p.pipeline.map(([a,b])=>`<li><span class="t">${h(a)}</span><span class="d">${h(b)}</span></li>`).join('')}</ol></div></section><section class="sec"><div class="container">${sectionHead('questions','what this project tests')}<div class="panel"><div class="panel-b" style="padding:0">${p.questions.map((q,i)=>`<div style="display:grid;grid-template-columns:42px 1fr;padding:14px 15px;border-bottom:1px solid var(--line)"><span style="color:var(--fg4);font-size:10px">Q${i+1}</span><span style="color:var(--fg2);font-size:12px">${h(q)}</span></div>`).join('')}</div></div></div></section>${ex.length?`<section class="sec"><div class="container">${sectionHead('related','lab')}<div class="panel"><div class="panel-b">${ex.map(e=>`<div style="display:flex;gap:13px;padding:7px 0;align-items:baseline"><span class="exp-id">[${e.id}]</span><span class="exp-title">${h(e.title)}</span><span class="tag ${e.tag}" style="margin-left:auto">${h(e.status)}</span></div>`).join('')}</div></div></div></section>`:''}<section class="sec"><div class="container"><div class="linkrow">${source?`<a class="btn solid" href="https://${source}" target="_blank" rel="noopener">source ↗</a>`:''}<a class="btn" href="#/knowledge">knowledge →</a><a class="btn" href="#/lab">lab →</a></div></div></section></div>`}
function Lab(){return `<div class="view"><section class="sec container">${sectionHead('lab',EXPERIMENTS.length+' entries')}<p class="lede dim mb">Not a changelog. Each entry is a question worth answering. Planned means planned. Built means I actually ran it.</p>${EXPERIMENTS.map(e=>`<details class="exp"><summary><span class="exp-id">[${e.id}]</span><span class="exp-title">${h(e.title)}</span><span class="tag ${e.tag}">${h(e.status)}</span></summary><div class="exp-body"><p>${h(e.body)}</p>${rows(e.spec)}</div></details>`).join('')}</section></div>`}
function Resources(){return `<div class="view"><section class="sec container">${sectionHead('resources','reference library')}<p class="lede dim mb">Concepts, mathematics, systems topics, and the layer underneath the frameworks — one reference, connected back to the work instead of scattered across pages.</p><div class="tree">${KNOWLEDGE.map(b=>`<details><summary>${h(b.branch)}<span class="cnt">${b.leaves.length} notes</span></summary><div class="leaves">${b.leaves.map(x=>`<div class="leaf"><span>${h(x.name)}</span><span class="m">${h(x.meta)}</span><span class="st ${x.st}">${x.st==='built'?'applied':'studying'}</span><span class="note">${h(x.note||'')}</span></div>`).join('')}</div></details>`).join('')}</div></section></div><section class="sec"><div class="container">${sectionHead('connections','knowledge ↔ work')}<div class="panel"><div class="panel-b" style="padding:0">${CONNECTIONS.map(([a,b,c])=>`<div style="display:grid;grid-template-columns:1fr auto 1fr auto 1fr;gap:9px;padding:12px 15px;border-bottom:1px solid var(--line);font-size:11.5px"><span>${h(a)}</span><span class="exp-id">→</span><span style="color:var(--fg2)">${h(b)}</span><span class="exp-id">→</span><span class="exp-id">${h(c)}</span></div>`).join('')}</div></div></div></section><section class="sec"><div class="container">${sectionHead('systems topics','below the abstraction')}<p class="lede dim mb">The computer is not a black box. This is the layer underneath Python and ML frameworks.</p><div class="panel"><div class="panel-h">topics</div><div class="panel-b">${rows(SYSTEMS_TOPICS)}</div></div></div></section><section class="sec"><div class="container">${sectionHead('memory','interactive')}<p class="lede dim mb">A small byte buffer. Click a cell and watch the pointer move.</p><div class="panel"><div class="panel-h">uint8_t buf[16] <span class="r">stack</span></div><div class="panel-b"><div class="memgrid" id="memgrid">${MEM.bytes.map((b,i)=>`<div class="cell" data-i="${i}"><span class="a">+${i.toString(16).padStart(2,'0')}</span>${b.toString(16).padStart(2,'0')}</div>`).join('')}</div><div class="readout"><div><div class="k">pointer</div><div class="v acc" id="ptr-addr">—</div></div><div><div class="k">*pointer</div><div class="v" id="ptr-val">—</div></div><div><div class="k">offset</div><div class="v" id="ptr-off">—</div></div></div></div></div></div></section><section class="sec"><div class="container">${sectionHead('address space','process')}<div class="panel"><div class="panel-b"><pre class="ascii"><span class="d">high addresses</span>
<span class="c">┌───────────────────────────┐</span>
<span class="c">│</span> stack          <span class="d">↓</span> locals / frames <span class="c">│</span>
<span class="c">├───────────────────────────┤</span>
<span class="c">│</span>             unused        <span class="c">│</span>
<span class="c">├───────────────────────────┤</span>
<span class="c">│</span> heap           <span class="d">↑</span> malloc    <span class="c">│</span>
<span class="c">├───────────────────────────┤</span>
<span class="c">│</span> data / bss                 <span class="c">│</span>
<span class="c">├───────────────────────────┤</span>
<span class="c">│</span> text / instructions        <span class="c">│</span>
<span class="c">└───────────────────────────┘</span>
<span class="d">low addresses</span></pre></div></div></div></section></div>`}
function Operator(){return `<div class="view"><section class="sec container">${sectionHead('operator','case file')}<p class="lede dim mb">Not a member list — a case file. LARPSOCIETY runs as a single-operator cell right now. The record is public because the work is public, not because there's a roster behind it.</p>${MEMBERS.map(memberCard).join('')}<p class="lede" style="margin-top:20px;max-width:70ch">${h(SITE.name)} — ${h(SITE.identity)}. Interested in the full path from mathematical idea to running program: Python and PyTorch to build ML systems, C to remove abstractions when it matters, mathematics to understand why any of it behaves the way it does.</p></section><section class="sec"><div class="container">${sectionHead('manifesto','working principles')}<ol class="chain"><li><span class="t">don't just use it</span><span class="d">understand the mechanism behind the abstraction</span></li><li><span class="t">measure it</span><span class="d">replace assumptions with experiments</span></li><li><span class="t">build it twice</span><span class="d">high-level implementation → lower-level implementation</span></li><li><span class="t">document the failure</span><span class="d">mistakes are part of the system's history</span></li></ol></div></section><section class="sec"><div class="container">${sectionHead('builds','projects')}<div class="linkrow"><a class="btn" href="#/projects">see all builds →</a></div></div></section><section class="sec"><div class="container">${sectionHead('contact','public endpoints')}<div class="panel"><div class="panel-b">${rows([["github",SITE.github.replace('https://','')],["email",SITE.email],["site","LARPSOCIETY / GitHub Pages"]])}</div></div></div></section></div>`}
function News(){return `<div class="view"><section class="sec container">${sectionHead('dispatches',NEWS.length+' entries')}<p class="lede dim mb">Field notes as things happen — AI, systems, OSINT. Written here, not aggregated from anywhere else.</p>${NEWS.map(newsItem).join('')}</section></div>`}
function NotFound(){return `<div class="view"><section class="sec container"><div class="kicker">// 404</div><h1 style="font-size:24px;margin-top:16px">route not found</h1><p class="lede dim" style="margin-top:12px">The machine looked. Nothing answered.</p><div class="linkrow"><a class="btn solid" href="#/">← return to index</a></div></section></div>`}
const ROUTES={'/':Home,'/news':News,'/resources':Resources,'/projects':Projects,'/lab':Lab,'/operator':Operator,'/knowledge':Resources,'/systems':Resources,'/about':Operator,'/portfolio':Operator,'/people':Operator};
const currentPath=()=>{const p=location.hash.replace(/^#/,'');if(!p||p==='/')return '/';return p.replace(/\/+$/,'')||'/'};
function mount(){const grid=document.getElementById('memgrid');if(!grid)return;const cells=[...grid.querySelectorAll('.cell')];let ptr=0;const paint=()=>{cells.forEach((c,i)=>c.classList.toggle('ptr',i===ptr));document.getElementById('ptr-addr').textContent='0x'+(MEM.base+ptr).toString(16);document.getElementById('ptr-val').textContent='0x'+MEM.bytes[ptr].toString(16).padStart(2,'0');document.getElementById('ptr-off').textContent='+'+ptr};cells.forEach((c,i)=>c.onclick=()=>{ptr=i;paint()});paint()}
function render(){const path=currentPath();const view=path.startsWith('/projects/')?ProjectDetail:ROUTES[path]||NotFound;app.innerHTML=view();document.querySelectorAll('.nav a').forEach(a=>{const t=a.getAttribute('href').replace(/^#/,'');a.classList.toggle('on',t==='/'?path==='/':path===t||path.startsWith(t+'/'))});window.scrollTo(0,0);mount()}
window.addEventListener('hashchange',render);render();
