const { SITE, PROJECTS, EXPERIMENTS } = window;
const app = document.getElementById('app');
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route = () => (location.hash.replace(/^#\/?/, '').split('/')[0] || 'home');
const project = slug => PROJECTS.find(p => p.slug === slug);
function shell(title, body){ return `<div class="page"><div class="wrap"><div class="eyebrow">${title}</div>${body}</div></div>`; }
function card(title, text, href, label='open'){ return `<a class="card" href="${href}"><div class="card-top"><span>${title}</span><span>↗</span></div><p>${text}</p><span class="small-link">${label}</span></a>`; }
function Home(){ return `<section class="home wrap"><div class="hero-copy"><div class="eyebrow">WELCOME TO THE CLUBHOUSE</div><h1>Come here to<br><em>try things.</em></h1><p>Code experiments, strange ideas, projects, people, and things worth messing with.</p><div class="hero-actions"><a class="pill hot" href="#/lab">enter the lab →</a><a class="pill" href="#/discover">see what's here</a></div></div><div class="orb"><span>✦</span><small>click around<br>nothing is sacred</small></div></section><section class="wrap feature-grid"><div class="feature feature-big"><span class="label">01 / FEATURED</span><h2>What happens when you<br>let a browser become a playground?</h2><p>Open an experiment. Drag something. Break something. Learn why it broke.</p><a href="#/lab">browse experiments →</a></div><div class="feature accent"><span class="label">02 / COMMUNITY</span><h2>People make<br>the place.</h2><p>Builders, artists, students, tinkerers, lurkers.</p><a href="#/people">meet the people →</a></div><div class="feature"><span class="label">03 / NEWS</span><h2>Small signals.<br>Big rabbit holes.</h2><p>Interesting things from around the internet, without the noise.</p><a href="#/news">read the signal →</a></div></section>`; }
function Discover(){ return shell('discover / start anywhere', `<div class="big-title"><h1>There is no<br>correct order.</h1><p>Pick something that looks interesting. The point is to wander.</p></div><div class="discovery-grid">${card('LAB','Interactive experiments you can actually touch.','#/lab','play with it →')}${card('PEOPLE','A loose network of curious humans.','#/people','see the network →')}${card('PROJECTS','Things people built because they wondered what would happen.','#/projects','open projects →')}${card('FORUM','Talk, ask, share, argue politely.','#/forum','join the conversation →')}${card('NEWS','A few things worth clicking today.','#/news','follow the rabbit hole →')}${card('SAHAND','The builder behind this place. His actual portfolio lives here.','#/sahand','view portfolio →')}</div>`); }
function Lab(){ return shell('lab / interactive playground', `<div class="big-title"><h1>Touch the<br><em>machinery.</em></h1><p>These are questions turned into things. Some are finished. Some are deliberately weird.</p></div><div class="lab-list">${EXPERIMENTS.map((e,i)=>`<details><summary><span class="num">${String(i+1).padStart(2,'0')}</span><b>${esc(e.title)}</b><span class="state ${e.tag}">${esc(e.status)}</span></summary><div class="lab-body"><p>${esc(e.body)}</p><div>${e.spec.map(x=>`<span>${esc(x[0])}: <b>${esc(x[1])}</b></span>`).join('')}</div></div></details>`).join('')}</div>`); }
function People(){ return shell('people / the network', `<div class="big-title"><h1>Not followers.<br><em>Participants.</em></h1><p>V1 keeps identity simple: profiles can be linked to public GitHub accounts. No custom account database needed.</p></div><div class="people-card"><div class="person-main"><div class="avatar">L</div><div><h2>LARPSOCIETY</h2><p>community hub · experiments · projects</p></div></div><div class="person-note">Want to be part of the network?<br><a href="#/forum">start a conversation →</a></div></div><div class="note">The site is intentionally static. Community persistence can live in GitHub Discussions / Giscus instead of pretending GitHub Pages is a backend.</div>`); }
function Projects(){ return shell('projects / built here', `<div class="big-title"><h1>Things made<br>to understand.</h1><p>Not a portfolio grid. Each project is an invitation to look closer.</p></div><div class="project-grid">${PROJECTS.map(p=>card(p.title,p.blurb,`#/projects/${p.slug}`,'open project →')).join('')}</div>`); }
function ProjectDetail(){ const slug=location.hash.split('/')[2]; const p=project(slug); if(!p)return shell('404',`<div class="big-title"><h1>Wrong rabbit hole.</h1><a href="#/projects">back to projects →</a></div>`); return shell(`project / ${p.title}`, `<div class="project-detail"><span class="label">${p.id} · ${p.status}</span><h1>${esc(p.title)}</h1><p class="lead">${esc(p.blurb)}</p><div class="tags">${p.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="detail-grid"><div><h3>THE IDEA</h3><p>Build it, inspect it, remove the abstraction where it gets interesting.</p>${p.pipeline.map(x=>`<div class="step"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</div><div><h3>QUESTIONS</h3>${p.questions.map((q,i)=>`<div class="question"><span>0${i+1}</span>${esc(q)}</div>`).join('')}<a class="pill hot" href="https://${p.spec.find(x=>x[0]==='source')?.[1] || 'github.com/sahandkhodayi'}" target="_blank" rel="noopener">source ↗</a></div></div></div>`); }
function Forum(){ return shell('forum / conversation', `<div class="big-title"><h1>Talk about<br><em>the weird stuff.</em></h1><p>For the first version, this points to an external discussion layer. Static hosting stays static; the conversation still persists.</p></div><div class="forum-box"><div><span>RECOMMENDED V1</span><h2>GitHub Discussions / Giscus</h2><p>No custom server. No database to maintain. Works with the GitHub Pages architecture.</p></div><a class="pill hot" href="https://github.com/sahandkhodayi" target="_blank" rel="noopener">open GitHub ↗</a></div>`); }
function News(){ return shell('news / today’s signal', `<div class="big-title"><h1>Less feed.<br><em>More signal.</em></h1><p>A lightweight static news shelf. No backend required; links can be curated or pulled from public feeds later.</p></div><div class="news-list"><article><span>01</span><div><b>Build something you can touch</b><p>Good experiments beat another wall of documentation.</p></div></article><article><span>02</span><div><b>Open the browser console</b><p>Sometimes the fastest way to understand a website is to poke it.</p></div></article><article><span>03</span><div><b>Follow a rabbit hole</b><p>There is no algorithm here telling you what you should care about.</p></div></article></div>`); }
function Sahand(){ return shell('sahand / portfolio', `<div class="portfolio"><span class="label">FOUNDER / BUILDER</span><h1>SAHAND<br><em>KHODAYI</em></h1><p class="lead">AI / ML · mathematics · C / systems</p><p class="bio">I build things to understand how they work — from neural networks and mathematical ideas to the C code and systems underneath them.</p><div class="portfolio-actions"><a class="pill hot" href="https://github.com/sahandkhodayi" target="_blank" rel="noopener">GitHub ↗</a><a class="pill" href="#/projects">my projects</a></div><div class="portfolio-work"><h2>SELECTED WORK</h2>${PROJECTS.map(p=>`<a href="#/projects/${p.slug}"><span>${esc(p.id)}</span><b>${esc(p.title)}</b><small>${esc(p.tags.join(' · '))}</small><i>↗</i></a>`).join('')}</div></div>`); }
function render(){ const r=route(); const view={home:Home,discover:Discover,lab:Lab,people:People,projects:Projects,forum:Forum,news:News,sahand:Sahand}[r]||Home; app.innerHTML=view(); document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#/'+r)); window.scrollTo(0,0); }
window.addEventListener('hashchange',render); render();
