window.SITE = {
  name: "sahand khodayi",
  handle: "sahand",
  identity: "ai / mathematics / c / systems",
  motto: "build it. break it. understand it.",
  github: "https://github.com/sahandkhodayi",
};

window.PROJECTS = [
  {
    id: "001",
    slug: "number-guesser",
    title: "Number Guesser",
    tagline: "Draw a digit. Watch a CNN read it.",
    blurb: "Handwritten digit recognition with a PyTorch-trained CNN and a C inference backend. The Lab demo runs the same pipeline in the browser.",
    tags: ["pytorch", "cnn", "c", "mnist"],
    status: "active",
    source: "github.com/sahandkhodayi/Number-Guesser",
    spec: [
      ["input", "28 × 28 grayscale"],
      ["model", "convolutional neural net"],
      ["training", "PyTorch / Python"],
      ["inference", "C"],
      ["interface", "Python GUI"],
    ],
    experiments: [
      { title: "PyTorch → C parity", body: "Run the same input through both implementations and compare the result." },
      { title: "MNIST preprocessing", body: "Test scaling, cropping, centering, and normalization — then break each one and watch accuracy drop." },
      { title: "Convolution explorer", body: "Move a 3×3 kernel across a digit and see each output value calculated." },
    ],
    questions: [
      "Can C reproduce the trained model exactly?",
      "How much does preprocessing matter?",
      "What happens between the model and the machine?",
    ],
  },
  {
    id: "002",
    slug: "nn-from-scratch",
    title: "NN from Scratch",
    tagline: "Build the network. Watch gradients move.",
    blurb: "A neural network written with Python and NumPy only — forward pass, backpropagation, and gradient descent, from first principles.",
    tags: ["python", "numpy", "backprop"],
    status: "built",
    source: "github.com/sahandkhodayi/NN-s-from-scratch-with-viuals",
    spec: [
      ["language", "Python + NumPy"],
      ["model", "neurons · layers · weights · biases"],
      ["training", "backpropagation + gradient descent"],
      ["visuals", "training and network state"],
    ],
    experiments: [
      { title: "Forward pass", body: "Watch values flow through a 3-4-2 network, node by node." },
      { title: "Activation comparison", body: "Compare ReLU, sigmoid, and tanh on the same input." },
      { title: "Backprop from scratch", body: "Implement the chain rule manually and watch the weights update." },
    ],
    questions: [
      "How does backprop work without autograd?",
      "How does the network change while training?",
    ],
  },
  {
    id: "003",
    slug: "ml-models-from-scratch",
    title: "ML Models",
    tagline: "Move the data. Watch the model learn.",
    blurb: "Linear and logistic regression implemented with NumPy, focused on the math behind learning — loss, gradients, and gradient descent.",
    tags: ["python", "numpy", "regression"],
    status: "built",
    source: "github.com/sahandkhodayi/Machine-learning-Models",
    spec: [
      ["language", "Python + NumPy"],
      ["models", "linear + logistic regression"],
      ["loss", "MSE + cross-entropy"],
      ["optimizer", "gradient descent"],
    ],
    experiments: [
      { title: "Gradient descent", body: "Drag the starting point and learning rate; watch the parameter slide toward the minimum." },
      { title: "Learning-rate lab", body: "Same starting point. Three learning rates. One diverges." },
      { title: "Normalization explorer", body: "Compare raw, standardized, and normalized features and see optimization speed change." },
    ],
    questions: [
      "How does normalization affect learning?",
      "Why does logistic regression use sigmoid?",
    ],
  },
  {
    id: "004",
    slug: "math-network",
    title: "Math Network",
    tagline: "Press train. Watch a curve appear.",
    blurb: "A PyTorch network that learns mathematical functions using Fourier-feature inputs. Same architecture, wildly different behaviour on high-frequency targets.",
    tags: ["pytorch", "mlp", "fourier"],
    status: "built",
    source: "github.com/sahandkhodayi/Math-function-approximation-with-NN",
    spec: [
      ["framework", "PyTorch"],
      ["model", "MLP"],
      ["encoding", "Fourier features"],
      ["activation", "Tanh"],
    ],
    experiments: [
      { title: "Function approximator", body: "Watch an MLP learn sin(x) from scratch." },
      { title: "Fourier features", body: "Compare a plain MLP with Fourier-feature inputs on a high-frequency target." },
    ],
    questions: [
      "Why are high-frequency functions harder?",
      "What changes when the input representation changes?",
    ],
  },
];